### ISSUE TITLE
AttributeError: 'exceptions.UnicodeDecodeError' object has no attribute 'text'

### ISSUE THREAD

**Issue by dhi20** [vimeo/vimeo.py#119] opened 2018-04-17 11:03 UTC
Hi,
Sorry if i'm missing something. I have tried to upload a video via vimeo.py on two different servers but without luck. I can amend existing video titles ect. but not upload. The reponse i get is as follows:

Traceback (most recent call last):
File "/root/vimeo/test1.py", line 13, in 
video_uri = v.upload('/home/fairlie/fairlie/webcam/fairlie/output.avi')
File "/usr/local/lib/python2.7/dist-packages/vimeo/upload.py", line 72, in upload
return self.__perform_tus_upload(filename, attempt)
File "/usr/local/lib/python2.7/dist-packages/vimeo/upload.py", line 147, in __perform_tus_upload
'Unexpected error when uploading through tus.'
File "/usr/local/lib/python2.7/dist-packages/vimeo/exceptions.py", line 88, in init
super(VideoUploadFailure, self).init(response, message)
File "/usr/local/lib/python2.7/dist-packages/vimeo/exceptions.py", line 27, in init
self.message = self.__get_message(response)
File "/usr/local/lib/python2.7/dist-packages/vimeo/exceptions.py", line 20, in __get_message
message = response.text
AttributeError: 'exceptions.UnicodeDecodeError' object has no attribute 'text'

Any guidance would be greatly appreciated.
Regards
Daniel

**Comment by TonyDobbs** [comment] 2018-05-02 05:12
@dhi20 I'm having the same issue. Were you able to resolve this problem?

**Comment by erunion** [comment] 2018-05-02 14:28
@TonyDobbs @dhi20 What version of Python are you all running?

**Comment by TonyDobbs** [comment] 2018-05-02 14:42
@erunion I am using Python 2.7.

@dhi20 Thanks for the response, I will continue investigating.

**Comment by erunion** [comment] 2018-05-03 14:57
Do you have a piece of code that can replicate the error every time? I need something I can test with, because I don't get this error when using the SDK.

**Comment by triump0870** [comment] 2018-05-07 19:41
I am also getting the same error @erunion when trying to upload from the local system using `tus` protocol. I have the following configuration
Python 2.7
pyvimeo 1.0.1
tuspy 0.2.2

**Comment by erunion** [comment] 2018-05-07 20:02
@triump0870 Do you have a video that replicates it every time that you can share with me to test?

**Comment by triump0870** [comment] 2018-05-07 20:45
@erunion I have found the issue, it's with `tuspy-0.2.2` when I downgraded it to `tuspy-0.2.1` it worked. I think `tuspy-0.2.2` is expecting Python 3.

**Comment by TonyDobbs** [comment] 2018-05-07 20:54
I never found the root caused, but it appeared to stem from an issue with the tus client. I downgraded from tuspy-0.2.2 to tuspy-0.2.1 and now it works.

**Comment by erunion** [comment] 2018-05-07 20:57
Fascianting, okay. I'll downgrade the client in the library and do some additional testing.

**Comment by triump0870** [comment] 2018-05-07 21:02
The actual problem lies with `perform` method in `TusRequest` class. In `tuspy-0.2.1` it is using `pycurl.Curl()` but in `tuspy-0.2.2` it is using `http.client` which is causing the error @erunion

**Comment by erunion** [comment] 2018-05-07 21:38
Ok cool, I can replicate it now with `tuspy-0.2.2`. Fixes incoming.

**Comment by erunion** [comment] 2018-05-07 21:50
@triump0870 @TonyDobbs @dhi20 A fix has been tagged to v1.0.2. Please let me know if that resolves it.

I just did a hard downgrade to tuspy to 0.2.1, and we can upgrade the library to support 0.2.2 later.

**Closed** 2018-05-08 14:01 UTC
Labels: bug
