### ISSUE TITLE
How to create subfolder/nasted-folder inside parent folder with Vimeo API using python?

### ISSUE THREAD

**Issue by entbappy** [vimeo/vimeo.py#178] opened 2022-01-26 14:38 UTC
I am trying vimeo API using python. I succeeded in creating and listing vimeo folder with vimeo API in just root location.

However, I cannot find how to create subfolders inside a parent folder in this API. I have read official documents but I could not find any related APIs. How to create subfolders/nasted folders in parent folders in vimeo using python?

![WhatsApp Image 2022-01-26 at 8 32 43 PM](https://user-images.githubusercontent.com/68845761/151182845-f7e36e67-8123-4f77-bda5-76baac09d971.jpeg)

**Comment by aaronm67** [comment] 2022-01-26 14:47
You can use a "parent_folder_uri" parameter on /me/projects.

parent_folder_uri = '/users/12345/projects/6789'

**Comment by aaronm67** [comment] 2022-01-26 15:19
Duplicate of #177, moving discussion there.

**Closed by aaronm67** 2022-01-26 15:19 UTC

**Comment by entbappy** [comment] 2022-01-26 15:26
> You can use a "parent_folder_uri" parameter on /me/projects.
> 
> So
> 
> POST /me/projects' data = { parent_folder_uri = '/users/12345/projects/6789', 'name' = 'NLP', etc }

Thank you so much ,, It worked😀👏
